pipeline {
    agent any
    tools {
        // Define the Maven installation from Jenkins configuration
        maven 'Maven 3.9.9'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your SCM
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project using Windows batch command                
                dir('payroll') {
                    sh 'mvn clean package'
                }

            }
        }
        
        stage('Test') {
            steps {
                // Run tests (if any) using Windows batch command
                dir('payroll') {
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                dir('payroll') {
                    sh 'copy target\\*.war /Users/josediaz/Tools/apache-tomcat-10.1.34/webapps'
                }
            }
        }
    }
}